development:
  adapter: postgresql
  database: names
  username: postgres # replace this with your own user name
  password: postgres # replace this with your own password
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000